### ISSUE TITLE
Use lwt jobs or Thread.create instead of Lwt_preemptive.detach

### ISSUE THREAD

**Issue by dsheets** [djs55/ocaml-hvsock#4]
`Lwt_preemptive.detach` requires the OCaml `threads` findlib package and blocks on the creation of new threads if the (shared) preemptive thread pool is full.

https://github.com/dsheets/ocaml-osx-cf/blob/master/lwt/cf_lwt.ml#L20 contains an implementation using `Thread.create` and `Lwt_preemptive.run_in_main` + `Lwt_stream` for synchronization.

https://github.com/dsheets/ocaml-unix-sys-stat/blob/master/lwt/unix_sys_stat_lwt_stubs.c contains an implementation using `lwt` jobs.

**Comment by djs55** [comment]
Good point -- I like your OCaml suggestion, I think I'd prefer to avoid writing yet more `lwt` jobs.
